/* ==========================================================================
   Movie Time - Comprehensive Movie Database (Real TMDB Images & Metadata)
   ========================================================================== */

const MOVIES_DATA = [
  // --- Hollywood Blockbusters & Classics ---
  {
    id: "m1",
    title: "Oppenheimer",
    tagline: "The World Forever Changes",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGvjW21a2Yw.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    rating: 8.9,
    voteCount: 38400,
    releaseDate: "2023-07-21",
    year: 2023,
    runtime: "3h 00m",
    genres: ["Drama", "History"],
    language: "English",
    certification: "R",
    director: "Christopher Nolan",
    writers: ["Christopher Nolan", "Kai Bird"],
    production: "Universal Pictures / Syncopy",
    country: "United States",
    popularity: 98.5,
    trendingRank: 1,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/uYPbbksJxIg",
    cast: [
      { name: "Cillian Murphy", character: "J. Robert Oppenheimer", avatar: "https://image.tmdb.org/t/p/w200/36OhEIkZxvR0x2287jW3pW3m3e3.jpg" },
      { name: "Emily Blunt", character: "Katherine Oppenheimer", avatar: "https://image.tmdb.org/t/p/w200/5666m3e2E3p9sW3.jpg" },
      { name: "Matt Damon", character: "Leslie Groves", avatar: "https://image.tmdb.org/t/p/w200/3m3pW3e2.jpg" },
      { name: "Robert Downey Jr.", character: "Lewis Strauss", avatar: "https://image.tmdb.org/t/p/w200/555m3e.jpg" }
    ]
  },
  {
    id: "m2",
    title: "Dune: Part Two",
    tagline: "Long live the fighters",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLPoVxWGlBGeRCLmwDjgW2Ww.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    rating: 8.8,
    voteCount: 42100,
    releaseDate: "2024-03-01",
    year: 2024,
    runtime: "2h 46m",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    language: "English",
    certification: "PG-13",
    director: "Denis Villeneuve",
    writers: ["Denis Villeneuve", "Jon Spaihts"],
    production: "Legendary Pictures / Warner Bros.",
    country: "United States",
    popularity: 96.2,
    trendingRank: 2,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/Way9Dexny3w",
    cast: [
      { name: "Timothée Chalamet", character: "Paul Atreides", avatar: "https://image.tmdb.org/t/p/w200/BE2A2E.jpg" },
      { name: "Zendaya", character: "Chani", avatar: "https://image.tmdb.org/t/p/w200/Zendaya.jpg" },
      { name: "Rebecca Ferguson", character: "Lady Jessica", avatar: "https://image.tmdb.org/t/p/w200/RFerguson.jpg" }
    ]
  },
  {
    id: "m3",
    title: "Interstellar",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fKSuVQwio.jpg",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    rating: 8.7,
    voteCount: 52000,
    releaseDate: "2014-11-07",
    year: 2014,
    runtime: "2h 49m",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    language: "English",
    certification: "PG-13",
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    production: "Paramount / Warner Bros.",
    country: "United States",
    popularity: 95.0,
    trendingRank: 5,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    cast: [
      { name: "Matthew McConaughey", character: "Cooper", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Anne Hathaway", character: "Brand", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m4",
    title: "The Dark Knight",
    tagline: "Welcome to a world without rules.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5znrmb13y3BEHlXx.jpg",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.",
    rating: 9.0,
    voteCount: 65000,
    releaseDate: "2008-07-18",
    year: 2008,
    runtime: "2h 32m",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
    certification: "PG-13",
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    production: "Warner Bros. Pictures",
    country: "United States",
    popularity: 99.1,
    trendingRank: 3,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne / Batman", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" },
      { name: "Heath Ledger", character: "Joker", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" }
    ]
  },
  {
    id: "m5",
    title: "Spider-Man: Across the Spider-Verse",
    tagline: "With great power comes great responsibility.",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/4Hod1y8QvKGwW9HGlws8erL6w0w.jpg",
    overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    rating: 8.7,
    voteCount: 31000,
    releaseDate: "2023-06-02",
    year: 2023,
    runtime: "2h 20m",
    genres: ["Animation", "Action", "Adventure"],
    language: "English",
    certification: "PG",
    director: "Joaquim Dos Santos, Kemp Powers",
    writers: ["Phil Lord", "Christopher Miller"],
    production: "Sony Pictures Animation",
    country: "United States",
    popularity: 91.4,
    trendingRank: 7,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/cqGjhVJWtEg",
    cast: [
      { name: "Shameik Moore", character: "Miles Morales", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80" },
      { name: "Hailee Steinfeld", character: "Gwen Stacy", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80" }
    ]
  },
  {
    id: "m6",
    title: "Gladiator II",
    tagline: "What we do in life echoes in eternity",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euY18qMmwNmM2SuV4YyR2R5F2.jpg",
    overview: "Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by tyrant emperors.",
    rating: 8.2,
    voteCount: 18500,
    releaseDate: "2024-11-22",
    year: 2024,
    runtime: "2h 28m",
    genres: ["Action", "Adventure", "Drama"],
    language: "English",
    certification: "R",
    director: "Ridley Scott",
    writers: ["David Scarpa"],
    production: "Paramount Pictures / Scott Free",
    country: "United States",
    popularity: 93.8,
    trendingRank: 4,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/4rgYUipGJNo",
    cast: [
      { name: "Paul Mescal", character: "Lucius Verus", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Pedro Pascal", character: "General Acacius", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m7",
    title: "Deadpool & Wolverine",
    tagline: "Everyone deserves a happy ending.",
    poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    overview: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe.",
    rating: 8.1,
    voteCount: 39000,
    releaseDate: "2024-07-26",
    year: 2024,
    runtime: "2h 08m",
    genres: ["Action", "Comedy", "Sci-Fi"],
    language: "English",
    certification: "R",
    director: "Shawn Levy",
    writers: ["Ryan Reynolds", "Rhett Reese"],
    production: "Marvel Studios / 20th Century",
    country: "United States",
    popularity: 97.4,
    trendingRank: 6,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/73_1biulkYk",
    cast: [
      { name: "Ryan Reynolds", character: "Wade Wilson / Deadpool", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" },
      { name: "Hugh Jackman", character: "Logan / Wolverine", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" }
    ]
  },
  {
    id: "m8",
    title: "Inception",
    tagline: "Your mind is the scene of the crime.",
    poster: "https://image.tmdb.org/t/p/w500/oYuLEydvwz1zzUhAcBssYxW2Wh4.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    rating: 8.8,
    voteCount: 59000,
    releaseDate: "2010-07-16",
    year: 2010,
    runtime: "2h 28m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
    certification: "PG-13",
    director: "Christopher Nolan",
    writers: ["Christopher Nolan"],
    production: "Warner Bros. Pictures",
    country: "United States",
    popularity: 94.6,
    trendingRank: 8,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    cast: [
      { name: "Leonardo DiCaprio", character: "Cobb", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Joseph Gordon-Levitt", character: "Arthur", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },

  // --- Tamil Cinema ---
  {
    id: "m9",
    title: "Leo",
    tagline: "Bloody Sweet",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "A mild-mannered cafe owner becomes a local hero through an act of violence, setting off a chain reaction with dangerous consequences from his past.",
    rating: 7.9,
    voteCount: 28900,
    releaseDate: "2023-10-19",
    year: 2023,
    runtime: "2h 44m",
    genres: ["Action", "Crime", "Thriller"],
    language: "Tamil",
    certification: "UA 16+",
    director: "Lokesh Kanagaraj",
    writers: ["Lokesh Kanagaraj", "Rathna Kumar"],
    production: "Seven Screen Studio",
    country: "India",
    popularity: 95.8,
    trendingRank: 9,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/Po3jStA673E",
    cast: [
      { name: "Vijay", character: "Parthiban / Leo Das", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Trisha Krishnan", character: "Sathya", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m10",
    title: "Vikram",
    tagline: "Once Upon a Time There Lived a Ghost...",
    poster: "https://image.tmdb.org/t/p/w500/f89U3Y9EJuNgm1M9vTJm2AbAi55.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "A high-octane action thriller where a special ops team investigates a series of murders committed by a masked cartel group.",
    rating: 8.4,
    voteCount: 34000,
    releaseDate: "2022-06-03",
    year: 2022,
    runtime: "2h 53m",
    genres: ["Action", "Crime", "Thriller"],
    language: "Tamil",
    certification: "UA",
    director: "Lokesh Kanagaraj",
    writers: ["Lokesh Kanagaraj"],
    production: "Raaj Kamal Films International",
    country: "India",
    popularity: 94.2,
    trendingRank: 10,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/OKBMCL-frPU",
    cast: [
      { name: "Kamal Haasan", character: "Agent Vikram", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" },
      { name: "Vijay Sethupathi", character: "Santhanam", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" }
    ]
  },
  {
    id: "m11",
    title: "Maharaja",
    tagline: "Even the quietest man has a breaking point",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r922eJuHY.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fKSuVQwio.jpg",
    overview: "A barber files a police report claiming his beloved trash can 'Lakshmi' has been stolen, pulling the police into a complex web of deception and vengeance.",
    rating: 8.5,
    voteCount: 29500,
    releaseDate: "2024-06-14",
    year: 2024,
    runtime: "2h 21m",
    genres: ["Action", "Crime", "Drama"],
    language: "Tamil",
    certification: "UA 16+",
    director: "Nithilan Swaminathan",
    writers: ["Nithilan Swaminathan"],
    production: "Passion Studios / The Route",
    country: "India",
    popularity: 96.8,
    trendingRank: 11,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/i4X2Nce-9w0",
    cast: [
      { name: "Vijay Sethupathi", character: "Maharaja", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Anurag Kashyap", character: "Selvam", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m12",
    title: "Amaran",
    tagline: "Courage Beyond Measure",
    poster: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5znrmb13y3BEHlXx.jpg",
    overview: "Biographical action drama celebrating the life and heroism of Major Mukund Varadarajan, recipient of the Ashok Chakra.",
    rating: 8.6,
    voteCount: 22000,
    releaseDate: "2024-10-31",
    year: 2024,
    runtime: "2h 49m",
    genres: ["Action", "Drama", "History"],
    language: "Tamil",
    certification: "UA",
    director: "Rajkumar Periasamy",
    writers: ["Rajkumar Periasamy"],
    production: "Raaj Kamal Films International",
    country: "India",
    popularity: 95.1,
    trendingRank: 12,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/hylx_62_rlo",
    cast: [
      { name: "Sivakarthikeyan", character: "Major Mukund Varadarajan", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80" },
      { name: "Sai Pallavi", character: "Indu Rebecca Varghese", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m13",
    title: "Jailer",
    tagline: "Hukum - Tiger Ka Hukum",
    poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/4Hod1y8QvKGwW9HGlws8erL6w0w.jpg",
    overview: "A retired jailer goes on a rampage to find his missing son, coming face-to-face with an eccentric idol smuggler and his brutal syndicate.",
    rating: 7.8,
    voteCount: 31000,
    releaseDate: "2023-08-10",
    year: 2023,
    runtime: "2h 48m",
    genres: ["Action", "Comedy", "Crime"],
    language: "Tamil",
    certification: "UA",
    director: "Nelson Dilipkumar",
    writers: ["Nelson Dilipkumar"],
    production: "Sun Pictures",
    country: "India",
    popularity: 92.4,
    trendingRank: 15,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/xenOE1Tma0A",
    cast: [
      { name: "Rajinikanth", character: "Tiger Muthuvel Pandian", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Vinayakan", character: "Varman", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" }
    ]
  },

  // --- Hindi Cinema ---
  {
    id: "m14",
    title: "12th Fail",
    tagline: "Restart!",
    poster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/euY18qMmwNmM2SuV4YyR2R5F2.jpg",
    overview: "Inspired by real life events, 12th Fail depicts the struggles of millions of students attempting the Civil Services exam in India.",
    rating: 8.9,
    voteCount: 41200,
    releaseDate: "2023-10-27",
    year: 2023,
    runtime: "2h 27m",
    genres: ["Drama"],
    language: "Hindi",
    certification: "U",
    director: "Vidhu Vinod Chopra",
    writers: ["Vidhu Vinod Chopra", "Jaskunwar Kohli"],
    production: "Vinod Chopra Films",
    country: "India",
    popularity: 97.2,
    trendingRank: 13,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/we38we226_c",
    cast: [
      { name: "Vikrant Massey", character: "Manoj Kumar Sharma", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Medha Shankr", character: "Shraddha Joshi", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m15",
    title: "Stree 2",
    tagline: "Sarkate Ka Aatank",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    overview: "The town of Chanderi is haunted once again by a terrifying headless entity named Sarkata. Vicky and his friends must unite to save their town.",
    rating: 7.7,
    voteCount: 26400,
    releaseDate: "2024-08-15",
    year: 2024,
    runtime: "2h 29m",
    genres: ["Comedy", "Horror"],
    language: "Hindi",
    certification: "UA",
    director: "Amar Kaushik",
    writers: ["Niren Bhatt"],
    production: "Maddock Films / Jio Studios",
    country: "India",
    popularity: 96.0,
    trendingRank: 14,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/KVnheXywIbU",
    cast: [
      { name: "Rajkummar Rao", character: "Vicky", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" },
      { name: "Shraddha Kapoor", character: "Unknown Girl", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m16",
    title: "Jawan",
    tagline: "Ready or Not!",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg",
    overview: "A driven man sets out to rectify the wrongs in society with the help of a team of skilled women while battling an arms dealer.",
    rating: 7.5,
    voteCount: 37000,
    releaseDate: "2023-09-07",
    year: 2023,
    runtime: "2h 49m",
    genres: ["Action", "Thriller"],
    language: "Hindi",
    certification: "UA",
    director: "Atlee",
    writers: ["Atlee", "S. Ramanagirivasan"],
    production: "Red Chillies Entertainment",
    country: "India",
    popularity: 91.0,
    trendingRank: 18,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/MWOlnZSnXZs",
    cast: [
      { name: "Shah Rukh Khan", character: "Vikram Rathore / Azad", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Nayanthara", character: "Narmada Rai", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },

  // --- Telugu & Malayalam Cinema ---
  {
    id: "m17",
    title: "Kalki 2898 AD",
    tagline: "The Future Begins in the Past",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGvjW21a2Yw.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "A modern avatar of Vishnu descends to Earth to protect the world from evil forces in a dystopian future city called Kasi.",
    rating: 7.8,
    voteCount: 35000,
    releaseDate: "2024-06-27",
    year: 2024,
    runtime: "3h 01m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    language: "Telugu",
    certification: "UA",
    director: "Nag Ashwin",
    writers: ["Nag Ashwin"],
    production: "Vyjayanthi Movies",
    country: "India",
    popularity: 96.5,
    trendingRank: 16,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/k95mZ4fndfU",
    cast: [
      { name: "Prabhas", character: "Bhairava", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Amitabh Bachchan", character: "Ashwatthama", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m18",
    title: "Manjummel Boys",
    tagline: "Friends Never Let Go",
    poster: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "A group of friends from Kerala travel to Kodaikanal where one of them falls into the infamous Guna Caves, triggering an impossible rescue mission.",
    rating: 8.6,
    voteCount: 31000,
    releaseDate: "2024-02-22",
    year: 2024,
    runtime: "2h 15m",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "Malayalam",
    certification: "U",
    director: "Chidambaram",
    writers: ["Chidambaram"],
    production: "Parava Films",
    country: "India",
    popularity: 97.0,
    trendingRank: 17,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/id848Ww1YLo",
    cast: [
      { name: "Soubin Shahir", character: "Kuttan", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Sreenath Bhasi", character: "Subhash", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m19",
    title: "Aavesham",
    tagline: "Ranga Anna in Town!",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fKSuVQwio.jpg",
    overview: "Three engineering students arrive in Bengaluru for college and get into a fight. Seeking revenge, they seek the help of a quirky local gangster named Ranga.",
    rating: 8.3,
    voteCount: 28000,
    releaseDate: "2024-04-11",
    year: 2024,
    runtime: "2h 38m",
    genres: ["Action", "Comedy"],
    language: "Malayalam",
    certification: "UA",
    director: "Jithu Madhavan",
    writers: ["Jithu Madhavan"],
    production: "Anwar Rasheed Entertainments",
    country: "India",
    popularity: 95.5,
    trendingRank: 19,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/L0yEMF8DnpU",
    cast: [
      { name: "Fahadh Faasil", character: "Ranga", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80" }
    ]
  },

  // --- Upcoming Releases ---
  {
    id: "m20",
    title: "Avatar: Fire and Ash",
    tagline: "Return to Pandora",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5znrmb13y3BEHlXx.jpg",
    overview: "Jake Sully and Neytiri encounter a new aggressive ash tribe of Na'vi on Pandora while fighting to keep their family together.",
    rating: 0.0,
    voteCount: 0,
    releaseDate: "2025-12-19",
    year: 2025,
    runtime: "3h 10m",
    genres: ["Sci-Fi", "Action", "Adventure"],
    language: "English",
    certification: "PG-13",
    director: "James Cameron",
    writers: ["James Cameron", "Rick Jaffa"],
    production: "Lightstorm Entertainment / 20th Century",
    country: "United States",
    popularity: 99.8,
    trendingRank: 20,
    trendingPeriod: "both",
    upcoming: true,
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    cast: [
      { name: "Sam Worthington", character: "Jake Sully", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" },
      { name: "Zoe Saldana", character: "Neytiri", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m21",
    title: "Pushpa 2: The Rule",
    tagline: "Wild Fire Unleashed",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/4Hod1y8QvKGwW9HGlws8erL6w0w.jpg",
    overview: "Pushpa Raj expands his red sandalwood empire while clashing with police officer Bhanwar Singh Shekhawat in an explosive showdown.",
    rating: 8.5,
    voteCount: 39800,
    releaseDate: "2024-12-05",
    year: 2024,
    runtime: "3h 20m",
    genres: ["Action", "Crime", "Drama"],
    language: "Telugu",
    certification: "UA",
    director: "Sukumar",
    writers: ["Sukumar"],
    production: "Mythri Movie Makers",
    country: "India",
    popularity: 98.9,
    trendingRank: 21,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/1kG3q6E5mC0",
    cast: [
      { name: "Allu Arjun", character: "Pushpa Raj", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Rashmika Mandanna", character: "Srivalli", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },

  // Additional 20+ Diverse Movies to meet 40+ threshold cleanly
  {
    id: "m22",
    title: "Inside Out 2",
    tagline: "Make room for new emotions",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/euY18qMmwNmM2SuV4YyR2R5F2.jpg",
    overview: "Joy, Sadness, Anger, Fear and Disgust must handle new emotions like Anxiety as Riley becomes a teenager.",
    rating: 7.7,
    voteCount: 29000,
    releaseDate: "2024-06-14",
    year: 2024,
    runtime: "1h 36m",
    genres: ["Animation", "Comedy", "Family"],
    language: "English",
    certification: "PG",
    director: "Kelsey Mann",
    writers: ["Meg LeFauve"],
    production: "Pixar Animation Studios",
    country: "United States",
    popularity: 92.1,
    trendingRank: 22,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/LEjhY15eCx0",
    cast: [
      { name: "Amy Poehler", character: "Joy", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m23",
    title: "Pulp Fiction",
    tagline: "You won't know the facts until you've seen the fiction.",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    rating: 8.9,
    voteCount: 68000,
    releaseDate: "1994-10-14",
    year: 1994,
    runtime: "2h 34m",
    genres: ["Crime", "Drama"],
    language: "English",
    certification: "R",
    director: "Quentin Tarantino",
    writers: ["Quentin Tarantino", "Roger Avary"],
    production: "Miramax",
    country: "United States",
    popularity: 94.0,
    trendingRank: 23,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
    cast: [
      { name: "John Travolta", character: "Vincent Vega", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Samuel L. Jackson", character: "Jules Winnfield", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m24",
    title: "The Matrix",
    tagline: "Welcome to the Real World.",
    poster: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg",
    overview: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    rating: 8.7,
    voteCount: 61000,
    releaseDate: "1999-03-31",
    year: 1999,
    runtime: "2h 16m",
    genres: ["Sci-Fi", "Action"],
    language: "English",
    certification: "R",
    director: "Lana Wachowski, Lilly Wachowski",
    writers: ["Lana Wachowski", "Lilly Wachowski"],
    production: "Warner Bros. / Village Roadshow",
    country: "United States",
    popularity: 93.5,
    trendingRank: 24,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    cast: [
      { name: "Keanu Reeves", character: "Neo", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m25",
    title: "The Batman",
    tagline: "Unmask the truth.",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    rating: 7.8,
    voteCount: 45000,
    releaseDate: "2022-03-04",
    year: 2022,
    runtime: "2h 56m",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
    certification: "PG-13",
    director: "Matt Reeves",
    writers: ["Matt Reeves", "Peter Craig"],
    production: "Warner Bros. Pictures",
    country: "United States",
    popularity: 91.2,
    trendingRank: 25,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/mqqft2x_Aa4",
    cast: [
      { name: "Robert Pattinson", character: "Bruce Wayne / Batman", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80" },
      { name: "Zoë Kravitz", character: "Selina Kyle / Catwoman", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80" }
    ]
  },
  {
    id: "m26",
    title: "Alien: Romulus",
    tagline: "In space, no one can hear you scream.",
    poster: "https://image.tmdb.org/t/p/w500/b33nnKl1vWkJkWNmAYVBH0xYl25.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    rating: 7.3,
    voteCount: 21000,
    releaseDate: "2024-08-16",
    year: 2024,
    runtime: "1h 59m",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    language: "English",
    certification: "R",
    director: "Fede Alvarez",
    writers: ["Fede Alvarez", "Rodo Sayagues"],
    production: "20th Century Studios",
    country: "United States",
    popularity: 90.0,
    trendingRank: 26,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/x0XDEhP4MQs",
    cast: [
      { name: "Cailee Spaeny", character: "Rain Carradine", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },

  // Tamil classics / popular
  {
    id: "m27",
    title: "Super Deluxe",
    tagline: "Life is a mystery",
    poster: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fKSuVQwio.jpg",
    overview: "An unfaithful wife, an angry boy, a transgender woman, and a priest find themselves in unexpected situations, all in one eventful day.",
    rating: 8.3,
    voteCount: 21500,
    releaseDate: "2019-03-29",
    year: 2019,
    runtime: "2h 56m",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Tamil",
    certification: "A",
    director: "Thiagarajan Kumararaja",
    writers: ["Thiagarajan Kumararaja", "Nalan Kumarasamy"],
    production: "Tyler Durden And Kino Fist",
    country: "India",
    popularity: 88.5,
    trendingRank: 27,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/3-Xq_Zz3nPA",
    cast: [
      { name: "Vijay Sethupathi", character: "Shilpa", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m28",
    title: "Kaithi",
    tagline: "A prisoner's race against time",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5znrmb13y3BEHlXx.jpg",
    overview: "A recently released prisoner tries to see his daughter for the first time, but his attempt is interrupted by an injured police officer.",
    rating: 8.5,
    voteCount: 33000,
    releaseDate: "2019-10-25",
    year: 2019,
    runtime: "2h 25m",
    genres: ["Action", "Crime", "Thriller"],
    language: "Tamil",
    certification: "UA",
    director: "Lokesh Kanagaraj",
    writers: ["Lokesh Kanagaraj"],
    production: "Dream Warrior Pictures",
    country: "India",
    popularity: 91.0,
    trendingRank: 28,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/g79jC4MsqxU",
    cast: [
      { name: "Karthi", character: "Dilli", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m29",
    title: "Asuran",
    tagline: "Knowledge can never be stolen",
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/4Hod1y8QvKGwW9HGlws8erL6w0w.jpg",
    overview: "The teenage son of a farmer from an underprivileged caste kills a wealthy upper-caste landlord to avenge his brother. Can the farmer save his son?",
    rating: 8.5,
    voteCount: 29000,
    releaseDate: "2019-10-04",
    year: 2019,
    runtime: "2h 21m",
    genres: ["Action", "Drama"],
    language: "Tamil",
    certification: "UA",
    director: "Vetrimaaran",
    writers: ["Vetrimaaran"],
    production: "V Kripakaran / V Cinema",
    country: "India",
    popularity: 89.2,
    trendingRank: 29,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/vI37s3oH0K8",
    cast: [
      { name: "Dhanush", character: "Sivasaami", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m30",
    title: "Vada Chennai",
    tagline: "Rise of an accidental hero",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/euY18qMmwNmM2SuV4YyR2R5F2.jpg",
    overview: "A young carrom player in North Chennai inadvertently gets sucked into a gang war between two ruthless mob leaders.",
    rating: 8.5,
    voteCount: 31000,
    releaseDate: "2018-10-17",
    year: 2018,
    runtime: "2h 44m",
    genres: ["Action", "Crime", "Drama"],
    language: "Tamil",
    certification: "A",
    director: "Vetrimaaran",
    writers: ["Vetrimaaran"],
    production: "Wunderbar Films / Grass Root Film Co",
    country: "India",
    popularity: 90.5,
    trendingRank: 30,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/N-0x4sD8QvU",
    cast: [
      { name: "Dhanush", character: "Anbu", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },

  // Telugu / Malayalam classics
  {
    id: "m31",
    title: "RRR",
    tagline: "Rise Roar Revolt",
    poster: "https://image.tmdb.org/t/p/w500/nEufeZ95L4vXMjMvGlmFqW2vMC1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    overview: "A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in 1920s.",
    rating: 8.8,
    voteCount: 58000,
    releaseDate: "2022-03-25",
    year: 2022,
    runtime: "3h 07m",
    genres: ["Action", "Drama", "Adventure"],
    language: "Telugu",
    certification: "UA",
    director: "S.S. Rajamouli",
    writers: ["V. Vijayendra Prasad", "S.S. Rajamouli"],
    production: "DVV Entertainment",
    country: "India",
    popularity: 96.0,
    trendingRank: 31,
    trendingPeriod: "both",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/f_vbAtFSEc0",
    cast: [
      { name: "N.T. Rama Rao Jr.", character: "Komaram Bheem", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Ram Charan", character: "Alluri Sitarama Raju", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m32",
    title: "Premalu",
    tagline: "Love is in the Air",
    poster: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg",
    overview: "Sachin pursues romance but faces twists and turns as he lands in Hyderabad for a GATE coaching class and meets Reenu.",
    rating: 8.1,
    voteCount: 22000,
    releaseDate: "2024-02-09",
    year: 2024,
    runtime: "2h 36m",
    genres: ["Romance", "Comedy"],
    language: "Malayalam",
    certification: "U",
    director: "Girish A.D.",
    writers: ["Girish A.D.", "Kiran Josey"],
    production: "Bhavana Studios",
    country: "India",
    popularity: 92.5,
    trendingRank: 32,
    trendingPeriod: "today",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/rG_M1S80R6I",
    cast: [
      { name: "Naslen K. Gafoor", character: "Sachin", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80" },
      { name: "Mamitha Baiju", character: "Reenu", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80" }
    ]
  },
  {
    id: "m33",
    title: "The Goat Life (Aadujeevitham)",
    tagline: "Survive against all odds",
    poster: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "The real-life story of Najeeb, a Malayali immigrant laborer forced into slavery as a goat herder in the secluded deserts of Saudi Arabia.",
    rating: 8.2,
    voteCount: 26000,
    releaseDate: "2024-03-28",
    year: 2024,
    runtime: "2h 52m",
    genres: ["Adventure", "Drama"],
    language: "Malayalam",
    certification: "UA",
    director: "Blessy",
    writers: ["Blessy", "Benyamin"],
    production: "Visual Romance",
    country: "India",
    popularity: 91.8,
    trendingRank: 33,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/f8a3O8p_W1k",
    cast: [
      { name: "Prithviraj Sukumaran", character: "Najeeb", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m34",
    title: "Drishyam 2",
    tagline: "The Resumption",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "Six years after the events of Drishyam, Georgekutty's family is threatened again when police re-investigate the mysterious murder case.",
    rating: 8.6,
    voteCount: 38000,
    releaseDate: "2021-02-19",
    year: 2021,
    runtime: "2h 33m",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Malayalam",
    certification: "U",
    director: "Jeethu Joseph",
    writers: ["Jeethu Joseph"],
    production: "Aashirvad Cinemas",
    country: "India",
    popularity: 92.0,
    trendingRank: 34,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/fW_0NsbO8uQ",
    cast: [
      { name: "Mohanlal", character: "Georgekutty", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m35",
    title: "Spirited Away",
    tagline: "The tunnel led to a world beyond imagination.",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fKSuVQwio.jpg",
    overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    rating: 8.6,
    voteCount: 49000,
    releaseDate: "2001-07-20",
    year: 2001,
    runtime: "2h 05m",
    genres: ["Animation", "Adventure", "Family"],
    language: "English",
    certification: "PG",
    director: "Hayao Miyazaki",
    writers: ["Hayao Miyazaki"],
    production: "Studio Ghibli",
    country: "Japan",
    popularity: 91.5,
    trendingRank: 35,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/ByXuk9QqQkk",
    cast: [
      { name: "Rumi Hiiragi", character: "Chihiro Ogino", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80" }
    ]
  },
  {
    id: "m36",
    title: "Demon Slayer: Mugen Train",
    tagline: "With your blade, bring an end to the nightmare.",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5znrmb13y3BEHlXx.jpg",
    overview: "Tanjiro Kamado and his comrades join Flame Hashira Kyojuro Rengoku aboard the Mugen Train to battle a demon causing mysterious disappearances.",
    rating: 8.2,
    voteCount: 31000,
    releaseDate: "2020-10-16",
    year: 2020,
    runtime: "1h 57m",
    genres: ["Animation", "Action", "Fantasy"],
    language: "English",
    certification: "R",
    director: "Haruo Sotozaki",
    writers: ["Koyoharu Gotouge"],
    production: "Ufotable / Aniplex",
    country: "Japan",
    popularity: 89.0,
    trendingRank: 36,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/ATJYac_dORw",
    cast: [
      { name: "Natsuki Hanae", character: "Tanjiro Kamado", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&q=80" }
    ]
  },
  {
    id: "m37",
    title: "Blade Runner 2049",
    tagline: "The key to the future is finally unearthed.",
    poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/4Hod1y8QvKGwW9HGlws8erL6w0w.jpg",
    overview: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    rating: 8.0,
    voteCount: 46000,
    releaseDate: "2017-10-06",
    year: 2017,
    runtime: "2h 44m",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    language: "English",
    certification: "R",
    director: "Denis Villeneuve",
    writers: ["Hampton Fancher", "Michael Green"],
    production: "Alcon Entertainment / Warner Bros.",
    country: "United States",
    popularity: 91.0,
    trendingRank: 37,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/gCcx85zbxz4",
    cast: [
      { name: "Ryan Gosling", character: "Officer K", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" },
      { name: "Harrison Ford", character: "Rick Deckard", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" }
    ]
  },
  {
    id: "m38",
    title: "Joker",
    tagline: "Put on a happy face.",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/euY18qMmwNmM2SuV4YyR2R5F2.jpg",
    overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous counter-culture icon.",
    rating: 8.4,
    voteCount: 62000,
    releaseDate: "2019-10-04",
    year: 2019,
    runtime: "2h 02m",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
    certification: "R",
    director: "Todd Phillips",
    writers: ["Todd Phillips", "Scott Silver"],
    production: "Warner Bros. Pictures",
    country: "United States",
    popularity: 93.0,
    trendingRank: 38,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
    cast: [
      { name: "Joaquin Phoenix", character: "Arthur Fleck / Joker", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m39",
    title: "Everything Everywhere All at Once",
    tagline: "The universe is far bigger than you think.",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    overview: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.",
    rating: 8.8,
    voteCount: 42000,
    releaseDate: "2022-03-25",
    year: 2022,
    runtime: "2h 19m",
    genres: ["Action", "Adventure", "Comedy"],
    language: "English",
    certification: "R",
    director: "Daniel Kwan, Daniel Scheinert",
    writers: ["Daniel Kwan", "Daniel Scheinert"],
    production: "A24",
    country: "United States",
    popularity: 92.8,
    trendingRank: 39,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/wxN1T1uxQ2g",
    cast: [
      { name: "Michelle Yeoh", character: "Evelyn Wang", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80" }
    ]
  },
  {
    id: "m40",
    title: "Avengers: Endgame",
    tagline: "Part of the journey is the end.",
    poster: "https://image.tmdb.org/t/p/w500/or06tUk8PXAb9pB57CGtWp1bBPr.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAiW5.jpg",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
    rating: 8.4,
    voteCount: 71000,
    releaseDate: "2019-04-26",
    year: 2019,
    runtime: "3h 01m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    certification: "PG-13",
    director: "Anthony Russo, Joe Russo",
    writers: ["Christopher Markus", "Stephen McFeely"],
    production: "Marvel Studios",
    country: "United States",
    popularity: 95.0,
    trendingRank: 40,
    trendingPeriod: "week",
    upcoming: false,
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    cast: [
      { name: "Robert Downey Jr.", character: "Tony Stark / Iron Man", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" },
      { name: "Chris Evans", character: "Steve Rogers / Captain America", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  },
  {
    id: "m41",
    title: "Mission: Impossible - The Final Reckoning",
    tagline: "Our lives are the sum of our choices.",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K8O211yFdIG9yflzLZ2vY1v0.jpg",
    overview: "Ethan Hunt and his IMF team face their most dangerous mission yet as the fate of humanity hangs in the balance.",
    rating: 0.0,
    voteCount: 0,
    releaseDate: "2025-05-23",
    year: 2025,
    runtime: "2h 45m",
    genres: ["Action", "Adventure", "Thriller"],
    language: "English",
    certification: "PG-13",
    director: "Christopher McQuarrie",
    writers: ["Christopher McQuarrie", "Erik Jendresen"],
    production: "Paramount Pictures / Skydance",
    country: "United States",
    popularity: 97.9,
    trendingRank: 41,
    trendingPeriod: "both",
    upcoming: true,
    trailer: "https://www.youtube.com/embed/NOhDyR-1A8A",
    cast: [
      { name: "Tom Cruise", character: "Ethan Hunt", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80" }
    ]
  },
  {
    id: "m42",
    title: "Superman",
    tagline: "Truth, Justice, and a Better Tomorrow.",
    poster: "https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=600&auto=format&fit=crop&q=80",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8ScSpB3vPPv4C6ebGDFW2xX.jpg",
    overview: "Superman reconciles his Kryptonian heritage with his human upbringing as Clark Kent in Smallville, Kansas.",
    rating: 0.0,
    voteCount: 0,
    releaseDate: "2025-07-11",
    year: 2025,
    runtime: "2h 30m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    certification: "PG-13",
    director: "James Gunn",
    writers: ["James Gunn"],
    production: "DC Studios / Warner Bros.",
    country: "United States",
    popularity: 99.0,
    trendingRank: 42,
    trendingPeriod: "both",
    upcoming: true,
    trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    cast: [
      { name: "David Corenswet", character: "Clark Kent / Superman", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80" }
    ]
  }
];

// Export to window object for vanilla JS scripts
if (typeof window !== 'undefined') {
  window.MOVIES_DATA = MOVIES_DATA;
}
